// Downloads Google Sans (fonts.google.com, SIL OFL) as self-hosted woff2 into web/fonts/ and
// writes web/css/fonts.css. Self-hosting keeps the app working offline in the PWA, Electron and
// Android builds and avoids a third-party request. Run with: npm run fonts
import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SUBSETS = new Set(['latin', 'latin-ext']);
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Google+Sans:wght@400;500;700&display=swap';
// A modern UA makes Google Fonts serve woff2
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36';

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();
const blocks = [...css.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[^}]+\})/g)]
  .filter(([, subset]) => SUBSETS.has(subset));
if (!blocks.length) throw new Error('No matching @font-face blocks; Google Fonts response changed?');

await mkdir(join(root, 'web/fonts'), { recursive: true });
const downloaded = new Map();
let out = '/* Generated by scripts/fetch-fonts.mjs. Google Sans, SIL Open Font License 1.1 */\n';
for (const [, subset, block] of blocks) {
  const weight = /font-weight: (\d+)/.exec(block)[1];
  const src = /url\((https:[^)]+\.woff2)\)/.exec(block)[1];
  if (!downloaded.has(src)) {
    const name = `google-sans-${subset}-${downloaded.size}.woff2`;
    const buf = Buffer.from(await (await fetch(src)).arrayBuffer());
    await writeFile(join(root, 'web/fonts', name), buf);
    downloaded.set(src, name);
    console.log(`  web/fonts/${name} (${(buf.length / 1024).toFixed(1)} KB)`);
  }
  out += `/* ${subset} ${weight} */\n` + block.replace(src, `../fonts/${downloaded.get(src)}`) + '\n';
}
await mkdir(join(root, 'web/css'), { recursive: true });
await writeFile(join(root, 'web/css/fonts.css'), out);
console.log('  web/css/fonts.css');
